services:
  - type: web
    name: ragpv-api
    env: python
    plan: free
    branch: main
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn src.api.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - fromGroup: ragpv-secrets

#  - type: worker
#    name: data-ingestion
#    env: python
#    plan: free
#    branch: main
#    buildCommand: "pip install -r requirements.txt"
#    startCommand: "python src/data_processing/excel_vectorizer.py"
#    envVars:
#      - key: PYTHON_VERSION
#        value: 3.11
#      - fromGroup: ragpv-secrets 